# Generated by Django 5.2.8 on 2025-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.IntegerField(),
        ),
    ]
