# Generated by Django 5.2.8 on 2025-12-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_remove_student_id_alter_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(max_length=50),
        ),
    ]
