# Generated by Django 5.2.8 on 2026-01-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="vlog_body",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="commnet",
            field=models.CharField(default="No comment", max_length=255, null=True),
        ),
    ]
