# Generated by Django 5.2.8 on 2025-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("guest_count", models.IntegerField()),
                ("reservation_date", models.DateTimeField(auto_now=True)),
                ("comments", models.TextField(max_length=1000)),
            ],
        ),
    ]
